# Numpy lab

1. Import the NUMPY package under the name np.


In [3]:
import numpy as np

2. Print the NUMPY version and the configuration.


In [4]:
print(np.version.version)

1.16.3


3. Generate a 2x3x5 2-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
a = np.random.random((2,3,5))


4. Print a.


In [6]:
print(a)


[[[0.10566699 0.20527703 0.06954337 0.62775993 0.80219044]
  [0.91381937 0.56306713 0.40734946 0.54959723 0.49408202]
  [0.15412576 0.03468272 0.08094949 0.99077313 0.51522509]]

 [[0.7925048  0.77917204 0.19171378 0.73163781 0.84185617]
  [0.61705007 0.83512153 0.46075759 0.4106242  0.86212588]
  [0.68118322 0.30664032 0.29932481 0.93680462 0.29483237]]]


5. Create a 5x2x3 5-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [7]:
b = np.ones([5,2,3])


6. Print b.



In [8]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


7. Do a and b have the same size? How do you prove that in Python code?

Yes, they have because the next line give us TRUE:




In [9]:
np.size(a) == np.size(b)


True

8.  Are you able to add a and b? Why or why not?

No, we can't because a and b do not have the same shape:



In [10]:
np.shape(a) == np.shape(b)

False

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to variable "c".

In [12]:
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


It works now because the shape of a and c are the same.


In [13]:
np.shape(c)

(2, 3, 5)

In [14]:
d = np.add(a, c)

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [16]:
print(a)


[[[0.10566699 0.20527703 0.06954337 0.62775993 0.80219044]
  [0.91381937 0.56306713 0.40734946 0.54959723 0.49408202]
  [0.15412576 0.03468272 0.08094949 0.99077313 0.51522509]]

 [[0.7925048  0.77917204 0.19171378 0.73163781 0.84185617]
  [0.61705007 0.83512153 0.46075759 0.4106242  0.86212588]
  [0.68118322 0.30664032 0.29932481 0.93680462 0.29483237]]]


In [17]:
print(d)

[[[1.10566699 1.20527703 1.06954337 1.62775993 1.80219044]
  [1.91381937 1.56306713 1.40734946 1.54959723 1.49408202]
  [1.15412576 1.03468272 1.08094949 1.99077313 1.51522509]]

 [[1.7925048  1.77917204 1.19171378 1.73163781 1.84185617]
  [1.61705007 1.83512153 1.46075759 1.4106242  1.86212588]
  [1.68118322 1.30664032 1.29932481 1.93680462 1.29483237]]]


For each row x in d, x is the corresponding row in a incremented by 1.


12. Multiply a and c. Assign the result to e.


In [18]:
e = np.multiply(a, c)

13. Does e equal to a? Why or why not?

In [19]:
print(e)

[[[0.10566699 0.20527703 0.06954337 0.62775993 0.80219044]
  [0.91381937 0.56306713 0.40734946 0.54959723 0.49408202]
  [0.15412576 0.03468272 0.08094949 0.99077313 0.51522509]]

 [[0.7925048  0.77917204 0.19171378 0.73163781 0.84185617]
  [0.61705007 0.83512153 0.46075759 0.4106242  0.86212588]
  [0.68118322 0.30664032 0.29932481 0.93680462 0.29483237]]]


In [20]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

e is not equal to a. However, each row of e is equal to each row of a.


14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [21]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [22]:
f = np.empty([2,3,5])


In [23]:
f

array([[[0.10566699, 0.20527703, 0.06954337, 0.62775993, 0.80219044],
        [0.91381937, 0.56306713, 0.40734946, 0.54959723, 0.49408202],
        [0.15412576, 0.03468272, 0.08094949, 0.99077313, 0.51522509]],

       [[0.7925048 , 0.77917204, 0.19171378, 0.73163781, 0.84185617],
        [0.61705007, 0.83512153, 0.46075759, 0.4106242 , 0.86212588],
        [0.68118322, 0.30664032, 0.29932481, 0.93680462, 0.29483237]]])

16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [24]:
def label(value):
    if value == d_min:
        return 0
    elif value > d_min and value < d_mean:
        return 25
    elif value == d_mean:
        return 50
    elif value > d_mean and value < d_max:
        return 75
    elif value == d_max:
        return 100

for i in range(2):
    for j in range(3):
        for k in range(5):
            f[i][j][k] = label(d[i][j][k])

17. Print d and f. Do you have your expected f?

In [25]:
print(f)

[[[ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.   0.  25. 100.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  25.  25.  75.  25.]]]


In [26]:
print(d)

[[[1.10566699 1.20527703 1.06954337 1.62775993 1.80219044]
  [1.91381937 1.56306713 1.40734946 1.54959723 1.49408202]
  [1.15412576 1.03468272 1.08094949 1.99077313 1.51522509]]

 [[1.7925048  1.77917204 1.19171378 1.73163781 1.84185617]
  [1.61705007 1.83512153 1.46075759 1.4106242  1.86212588]
  [1.68118322 1.30664032 1.29932481 1.93680462 1.29483237]]]


18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [27]:
# First we create an empty array h having the same shape as d which contains only strings

h= np.empty([2, 3, 5],dtype ='str')



In [29]:
def label_str(value):
    
    '''
    This function assign a string to a value according to the values of the array d
    '''
    
    if value == d_min:
        return 'A'
    elif value > d_min and value < d_mean:
        return 'B'
    elif value == d_mean:
        return 'C'
    elif value > d_mean and value < d_max:
        return 'D'
    elif value == d_max:
        return 'E'

In [30]:
# Here we label the array h according to the function label_str.

for i in range(2):
    for j in range(3):
        for k in range(5):
            h[i][j][k] = label_str(d[i][j][k])


In [31]:
print(h)

[[['B' 'B' 'B' 'D' 'D']
  ['D' 'D' 'B' 'D' 'B']
  ['B' 'A' 'B' 'E' 'B']]

 [['D' 'D' 'B' 'D' 'D']
  ['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'B']]]


In [32]:
type(h)

numpy.ndarray